import type { Metadata } from "next";
import React from 'react';
import Link from 'next/link';
import { Gavel, ShieldAlert, Lock, CreditCard, Ban, Globe } from 'lucide-react';

export const metadata: Metadata = {
  title: "Terms of Service",
  description: "NeuralRouting terms of service. Review our usage policies, subscription terms, and acceptable use guidelines for our AI routing platform.",
  robots: { index: true, follow: false },
  openGraph: { title: "Terms of Service | NeuralRouting.io", url: "https://neuralrouting.io/terms" },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#050505]">
      <div className="max-w-4xl mx-auto py-20 px-6 text-slate-400 leading-relaxed font-sans">
        <div className="text-center mb-16">
          <div className="bg-blue-500/10 w-16 h-16 rounded-2xl flex items-center justify-center mx-auto mb-4 border border-blue-500/20">
            <Gavel size={32} className="text-blue-500" />
          </div>
          <h1 className="text-4xl font-black text-white mb-2 tracking-tight uppercase">Terms of Service</h1>
          <p className="text-slate-500 italic">Effective Date: April 3, 2026</p>
        </div>

        <div className="space-y-12">

          {/* 1. Nature of Service */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <Globe size={20} className="text-blue-400" /> 1. Nature of the Service
            </h2>
            <p className="mb-4">
              NeuralRouting acts as an <strong className="text-white">intermediary routing infrastructure</strong>. By using this service, you acknowledge that NeuralRouting does not generate AI content but optimizes the delivery and selection of third-party models (e.g., OpenAI, Anthropic).
            </p>
            <div className="bg-slate-900/50 p-4 border-l-4 border-blue-500 rounded-r-xl italic text-sm">
              NeuralRouting is not liable for the accuracy, quality, or safety of responses generated by third-party providers.
            </div>
          </section>

          {/* 2. Acceptable Use */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <ShieldAlert size={20} className="text-blue-400" /> 2. Acceptable Use
            </h2>
            <p className="mb-4">
              You agree not to use NeuralRouting to transmit, generate, or facilitate content that is unlawful, harmful, abusive, defamatory, or that infringes upon any third-party intellectual property rights. We reserve the right to suspend or terminate any account found in violation of this policy without notice or refund.
            </p>
            <ul className="list-disc pl-5 space-y-2 text-sm">
              <li>You may not resell, sublicense, or redistribute access to the NeuralRouting API without prior written consent.</li>
              <li>Automated abuse, rate-limit circumvention, or attempts to reverse-engineer the routing logic are strictly prohibited.</li>
              <li>You are solely responsible for ensuring your use of the service complies with applicable local laws and regulations.</li>
            </ul>
          </section>

          {/* 3. API Security */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <Lock size={20} className="text-blue-400" /> 3. Security &amp; API Usage
            </h2>
            <p>
              You are entirely responsible for maintaining the confidentiality of your API keys. Any activity performed via your credentials will be deemed your legal and financial responsibility. You agree to notify us immediately of any unauthorized use at <strong className="text-white">support@neuralrouting.io</strong>. NeuralRouting will not be held liable for losses resulting from compromised credentials.
            </p>
          </section>

          {/* 4. Billing */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <CreditCard size={20} className="text-blue-400" /> 4. Billing, Credits &amp; Refunds
            </h2>
            <ul className="list-disc pl-5 space-y-3">
              <li><strong className="text-white">Pay-As-You-Go:</strong> Usage is billed based on actual token consumption. Credits are deducted in real-time per request.</li>
              <li><strong className="text-white">Finality:</strong> All credit purchases are non-refundable. NeuralRouting pays upstream providers immediately; therefore, we cannot reverse credit transactions.</li>
              <li><strong className="text-white">Reservation System:</strong> We reserve an estimated credit amount at the start of each request to ensure balance sufficiency. Unused reservations are released upon request completion.</li>
              <li><strong className="text-white">Free Tier:</strong> Free credits are provided at NeuralRouting&apos;s sole discretion and may be modified or revoked at any time without prior notice.</li>
            </ul>
          </section>

          {/* 5. Intellectual Property */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <Globe size={20} className="text-blue-400" /> 5. Intellectual Property
            </h2>
            <p>
              All trademarks, logos, and service names associated with NeuralRouting are the exclusive property of NeuralRouting. Nothing in these Terms grants you any right to use our branding without express written permission. You retain ownership of any content or data you submit through the API, and grant NeuralRouting a limited license to process such data solely for the purpose of providing the service.
            </p>
          </section>

          {/* 6. Limitation of Liability */}
          <section className="bg-red-900/10 border border-red-500/20 p-8 rounded-3xl">
            <h2 className="text-xl font-bold text-red-400 mb-4 flex items-center gap-2 uppercase">
              <Ban size={20} /> 6. Limitation of Liability
            </h2>
            <p className="text-sm font-medium leading-relaxed mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, NEURALROUTING SHALL NOT BE LIABLE FOR ANY INDIRECT, CONSEQUENTIAL, INCIDENTAL, SPECIAL, OR PUNITIVE DAMAGES (INCLUDING LOSS OF PROFITS, DATA, GOODWILL, OR BUSINESS INTERRUPTION) RESULTING FROM:
            </p>
            <ul className="text-xs list-disc pl-5 space-y-1">
              <li>Provider-side outages, rate limits, or service degradation by OpenAI, Anthropic, or any other third-party model provider.</li>
              <li>Inaccuracies, hallucinations, or harmful content in AI-generated output.</li>
              <li>Unauthorized access to your account due to poor credential management on your part.</li>
              <li>Interruptions caused by force majeure, including but not limited to natural disasters, cyberattacks, or infrastructure failures.</li>
            </ul>
            <p className="text-xs mt-4 text-slate-500">
              Our total aggregate liability shall not exceed the amount you paid to NeuralRouting in the 30 days prior to the event giving rise to the claim.
            </p>
          </section>

          {/* 7. Modifications */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <ShieldAlert size={20} className="text-blue-400" /> 7. Modifications to the Service &amp; Terms
            </h2>
            <p>
              NeuralRouting reserves the right to modify these Terms at any time. We will provide reasonable notice of significant changes via email or an in-app notification. Continued use of the service after such notice constitutes your acceptance of the updated Terms. If you do not agree to the revised Terms, you must discontinue use immediately.
            </p>
          </section>

          {/* 8. Governing Law */}
          <section>
            <h2 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
              <Gavel size={20} className="text-blue-400" /> 8. Governing Law
            </h2>
            <p>
              These Terms shall be governed by the laws of <strong className="text-white">Argentina</strong>. Any disputes arising from these Terms shall be settled exclusively in the competent courts of <strong className="text-white">Gobernador Virasoro, Corrientes</strong>. If any provision of these Terms is found unenforceable, the remaining provisions shall remain in full force and effect.
            </p>
          </section>

          {/* Footer */}
          <div className="pt-12 border-t border-slate-800 text-center">
            <p className="mb-2 text-sm">Last updated: April 3, 2026.</p>
            <p className="mb-8 text-sm">By integrating our API, you confirm you have read and accepted these Terms in their entirety.</p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <Link href="/" className="inline-block bg-white text-black px-8 py-3 rounded-full font-black hover:bg-slate-200 transition-all shadow-xl shadow-white/5">
                Back to Home
              </Link>
              <Link href="/privacy" className="inline-block border border-slate-700 text-slate-300 px-8 py-3 rounded-full font-black hover:border-blue-500 hover:text-white transition-all">
                Privacy Policy
              </Link>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
